// 全站設定：類別 metadata、欄位 schema、CSV 連結
// 第二階段把 csvUrl 換成 Google Sheet「發布到網路 → CSV」連結即可

export const SITE = {
  name: '護理職場透明化運動',
  tagline: '讓真實的職場資訊，被下一個護理師看見',
  contactEmail: 'transparentnursing@example.org',
  lastUpdated: '自動依資料動態計算',
};

// 共用欄位（所有類別都會出現）
export const COMMON_FIELDS = [
  { key: 'timestamp', label: '填寫時間', type: 'datetime' },
  { key: 'institutionType', label: '機構類別', type: 'enum',
    options: ['醫學中心', '區域醫院', '地區醫院', '診所', '其他'] },
  { key: 'institutionName', label: '機構名稱', type: 'string' },
  { key: 'unitName', label: '單位名稱', type: 'string' },
  { key: 'location', label: '工作地點', type: 'string' },
  { key: 'jobTitle', label: '職稱', type: 'string' },
  { key: 'weeklyHours', label: '每週工時', type: 'range',
    options: ['35-40', '40-45', '45-50', '50-55', '55-60', '60+'] },
  { key: 'overtimePolicy', label: '加班費合規', type: 'enum',
    options: ['一律給', '合理範圍給', '主管判斷', '一律不給'] },
  { key: 'yearsCurrent', label: '現職年資', type: 'number' },
  { key: 'yearsTotal', label: '累計年資', type: 'number' },
  { key: 'annualSalary', label: '近一年年薪 (萬)', type: 'number' },
  { key: 'monthlyBase', label: '月底薪+津貼 (千)', type: 'number' },
  { key: 'annualBonus', label: '全年獎金 (萬)', type: 'number' },
  { key: 'workAtmosphere', label: '工作氣氛 (1-5)', type: 'number' },
  { key: 'promotion', label: '升遷前景', type: 'enum',
    options: ['機會多', '普通', '難以升遷'] },
  { key: 'recommendIndex', label: '推薦指數 (1-5)', type: 'number' },
  { key: 'comment', label: '個人短評', type: 'text' },
];

export const CATEGORIES = [
  {
    slug: 'ward',
    name: '病房',
    short: '病房',
    color: '#F4A261',
    accent: '#FCE2C8',
    description: '一般病房護理，含內外婦兒精神安寧多種屬性，是護理人力配置的主力。',
    icon: 'bed',
    csvUrl: 'data/mock/ward.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'wardType', label: '病房類型', type: 'enum',
        options: ['內科', '外科', '婦產', '兒科', '精神', '安寧', '混合'] },
      { key: 'dayShiftRatio', label: '白班護病比', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜護病比', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜護病比', type: 'string' },
      { key: 'leaderSupport', label: 'Leader 協助', type: 'enum',
        options: ['全班協助', '部分協助', '無'] },
      { key: 'invasiveDuties', label: '侵入性處置', type: 'string' },
    ],
  },
  {
    slug: 'icu',
    name: '加護病房',
    short: 'ICU',
    color: '#2E86AB',
    accent: '#A8DADC',
    description: '高密度照護重症病人，呼吸器、血流動力監測、各式維生管路的第一線。',
    icon: 'activity',
    csvUrl: 'data/mock/icu.csv',
    formUrl: 'https://docs.google.com/forms/d/16GCaSbn4IgsQP5IVUFREw9xtDS-3VW0sR2SPv-9KYv4',
    formStatus: 'live',
    specificFields: [
      { key: 'icuType', label: 'ICU 類型', type: 'enum',
        options: ['內科', '外科', '心臟', '神經', '兒童', '混合'] },
      { key: 'dayShiftRatio', label: '白班人均', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜人均', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜人均', type: 'string' },
      { key: 'ventilatorCare', label: '呼吸器照護', type: 'enum',
        options: ['全部', '多數', '少數', '無'] },
    ],
  },
  {
    slug: 'er',
    name: '急診',
    short: '急診',
    color: '#E63946',
    accent: '#FAD2CF',
    description: '檢傷、重症、留觀並行，工作節奏快、變動大，暴力風險不可忽視。',
    icon: 'siren',
    csvUrl: 'data/mock/er.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'erLevel', label: '急診級別', type: 'enum',
        options: ['重度級', '中度級', '一般級'] },
      { key: 'triageRatio', label: '檢傷人均', type: 'string' },
      { key: 'criticalRatio', label: '重症區人均', type: 'string' },
      { key: 'observationRatio', label: '留觀人均', type: 'string' },
      { key: 'violenceFreq', label: '暴力事件頻率', type: 'enum',
        options: ['每週', '每月', '每季', '罕見'] },
    ],
  },
  {
    slug: 'or',
    name: '手術房',
    short: '手術房',
    color: '#FF6B9D',
    accent: '#FDD5E2',
    description: '麻醉協助、刷手、流動、恢復室照護，高專科高責任的開刀第一線。',
    icon: 'scissors',
    csvUrl: 'data/mock/or.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'orSpecialty', label: '主要科別', type: 'enum',
        options: ['一般外科', '心臟外科', '神經外科', '骨科', '婦產', '泌尿', '整形外科', '兒外', '眼科', '耳鼻喉', '混合'] },
      { key: 'orRole', label: '工作角色', type: 'enum',
        options: ['流動護理師', '刷手護理師', '恢復室', '麻醉護理', '混合輪替'] },
      { key: 'dailyCases', label: '每日刀數', type: 'string' },
      { key: 'roomCount', label: '手術室數量', type: 'string' },
      { key: 'dayShiftRatio', label: '白班配置 (護理師:刀台)', type: 'string' },
      { key: 'onCallSystem', label: '值班/On-call', type: 'enum',
        options: ['有，常被 call 回', '有，少被 call', '無'] },
    ],
  },
  {
    slug: 'outpatient',
    name: '門診',
    short: '門診',
    color: '#9D4EDD',
    accent: '#E0CFF7',
    description: '依診所/醫院規模差異極大，含掛號、檢查協助、衛教與行政事務。',
    icon: 'calendar-check',
    csvUrl: 'data/mock/outpatient.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'clinicType', label: '門診類型', type: 'enum',
        options: ['內科系', '外科系', '專科', '聯合門診', '健檢中心'] },
      { key: 'registrationPerSession', label: '每診平均掛號', type: 'string' },
      { key: 'staffPerClinic', label: '每診人力', type: 'string' },
      { key: 'supportProcedures', label: '協助處置', type: 'string' },
      { key: 'hasOvertime', label: '有無加班', type: 'enum',
        options: ['每日', '偶爾', '罕見', '無'] },
    ],
  },
  {
    slug: 'dialysis',
    name: '洗腎室',
    short: '洗腎',
    color: '#06A77D',
    accent: '#C6E8DC',
    description: '血液透析、腹膜透析的長期照護單位，值班與待命制度差異大。',
    icon: 'droplet',
    csvUrl: 'data/mock/dialysis.csv',
    formUrl: 'participate-dialysis.html',
    formStatus: 'live',
    specificFields: [
      { key: 'dialysisType', label: '透析類別', type: 'enum',
        options: ['血液透析', '腹膜透析', '兩者皆有'] },
      { key: 'hdRatio', label: 'HD 床護比', type: 'string' },
      { key: 'pdCount', label: 'PD 人數比', type: 'string' },
      { key: 'batchShift', label: '批班制度', type: 'enum', options: ['有', '無'] },
      { key: 'onCallType', label: '值班型態', type: 'string' },
      { key: 'onCallRotation', label: '值班輪值方式', type: 'string' },
      { key: 'restInterval11h', label: '值班 11 小時間隔', type: 'enum', options: ['有', '無'] },
      { key: 'onCallPay', label: '未出勤值班費', type: 'string' },
      { key: 'workDuties', label: '業務內容', type: 'multi' },
      { key: 'specialBenefits', label: '特殊福利', type: 'text' },
    ],
  },
  {
    slug: 'psych',
    name: '精神科',
    short: '精神科',
    color: '#4F46E5',
    accent: '#C7D2FE',
    description: '專指精神科病房（含精神急性、慢性、日間照護等）。涉及保護室、約束/隔離與人權保障，照護重點在功能復健與生活尊嚴，邏輯與一般病房截然不同。',
    icon: 'brain',
    csvUrl: 'data/mock/psych.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'psychType', label: '病房類型', type: 'enum',
        options: ['精神急性病房', '精神慢性病房', '日間照護單位', '社區精神復健', '兒童青少年精神', '老年精神', '成癮戒治'] },
      { key: 'dayShiftRatio', label: '白班護病比', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜護病比', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜護病比', type: 'string' },
      { key: 'hasProtectionRoom', label: '保護室規格', type: 'enum',
        options: ['符合新規格', '較舊但堪用', '無'] },
      { key: 'teamSupport', label: '跨專業團隊', type: 'enum',
        options: ['完整（心理/職能/社工/醫師）', '部分（缺 1-2 種）', '主要靠護理'] },
      { key: 'restraintFreq', label: '約束/隔離頻率', type: 'enum',
        options: ['每日多次', '每週數次', '偶爾', '罕見'] },
      { key: 'violenceFreq', label: '暴力/自傷事件頻率', type: 'enum',
        options: ['每週', '每月', '每季', '罕見'] },
    ],
  },
  {
    slug: 'special',
    name: '檢查/介入',
    short: '檢查/介入',
    color: '#14B8A6',
    accent: '#B7E9E1',
    description: '心導管、內視鏡、血管攝影等檢查與介入治療單位，常需 on-call、面對輻射暴露。',
    icon: 'zap',
    csvUrl: 'data/mock/special.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'specialType', label: '單位類型', type: 'enum',
        options: ['心導管室', '電燒室 (EP Lab)', '內視鏡室', '胃鏡室', '血管攝影室', '介入治療中心', '高壓氧', '其他'] },
      { key: 'dailyCases', label: '每日案件數', type: 'string' },
      { key: 'onCallRequired', label: 'On-call 制度', type: 'enum',
        options: ['有，常被 call', '有，少被 call', '無'] },
      { key: 'radiationExposure', label: '輻射暴露', type: 'enum',
        options: ['高頻率', '中等', '少量', '無'] },
      { key: 'dayShiftRatio', label: '白班人均', type: 'string' },
    ],
  },
  {
    slug: 'other',
    name: '其他',
    short: '其他',
    color: '#64748B',
    accent: '#D1D9E2',
    description: '凡不屬於前述場域的護理相關職務都歸在這裡：專科護理師、社區／居家護理、長照機構、學校護理師、月子中心、捐血中心、公共衛生等；也涵蓋較少被看見的護理職涯——職業安全衛生（廠護／職護）、臨床研究（CRA 臨床監測員、SC／CRC 試驗協調／研究護理師）、藥廠與醫材廠等。',
    icon: 'briefcase-medical',
    csvUrl: 'data/mock/other.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'customCategory', label: '單位類別', type: 'string' },
      { key: 'serviceTarget', label: '服務對象', type: 'string' },
      { key: 'mainDuties', label: '主要業務', type: 'string' },
      { key: 'dayShiftRatio', label: '人力配置', type: 'string' },
    ],
  },
];

export function getCategory(slug) {
  return CATEGORIES.find((c) => c.slug === slug) || null;
}

export function getAllFields(slug) {
  const cat = getCategory(slug);
  if (!cat) return COMMON_FIELDS;
  return [...COMMON_FIELDS, ...cat.specificFields];
}
