// 全站設定：類別 metadata、欄位 schema、CSV 連結
// 第二階段把 csvUrl 換成 Google Sheet「發布到網路 → CSV」連結即可

export const SITE = {
  name: '護理職場透明化運動',
  tagline: '讓真實的職場資訊，被下一個護理師看見',
  contactEmail: 'transparentnursing@example.org',
  lastUpdated: '自動依資料動態計算',
  // Disqus 留言：到 disqus.com 建站取得 shortname 後填入（留空＝顯示「設定中」提示、不載入）。
  // 別忘了到 Disqus 後台 Settings → Advanced → Trusted Domains 加入 ycchou.github.io。
  disqusShortname: '',
};

// 共用欄位（所有類別都會出現）
export const COMMON_FIELDS = [
  { key: 'timestamp', label: '填寫時間', type: 'datetime' },
  { key: 'institutionType', label: '機構類別', type: 'enum',
    options: ['醫學中心', '區域醫院', '地區醫院', '診所', '其他'] },
  { key: 'institutionName', label: '機構名稱', type: 'string' },
  { key: 'unitName', label: '單位名稱', type: 'string' },
  { key: 'location', label: '工作地點', type: 'string' },
  { key: 'jobTitle', label: '職稱', type: 'string' },
  { key: 'weeklyHours', label: '每週工時', type: 'range',
    options: ['35-40', '40-45', '45-50', '50-55', '55-60', '60+'] },
  { key: 'overtimePolicy', label: '加班費合規', type: 'enum',
    options: ['一律給', '合理範圍給', '主管判斷', '一律不給'] },
  { key: 'yearsCurrent', label: '現職年資', type: 'number' },
  { key: 'yearsTotal', label: '累計年資', type: 'number' },
  { key: 'annualSalary', label: '近一年年薪 (萬)', type: 'number' },
  { key: 'monthlyBase', label: '月底薪+津貼 (千)', type: 'number' },
  { key: 'annualBonus', label: '全年獎金 (萬)', type: 'number' },
  { key: 'workAtmosphere', label: '工作氣氛 (1-5)', type: 'number' },
  { key: 'promotion', label: '升遷前景', type: 'enum',
    options: ['機會多', '普通', '難以升遷'] },
  { key: 'recommendIndex', label: '推薦指數 (1-5)', type: 'number' },
  { key: 'comment', label: '個人短評', type: 'text' },
];

export const CATEGORIES = [
  {
    slug: 'ward',
    name: '病房',
    short: '病房',
    color: '#F4A261',
    accent: '#FCE2C8',
    description: '收治內、外、婦、兒、安寧等各科住院病人，是護理人力配置的主力。',
    icon: 'bed',
    csvUrl: 'data/mock/ward.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'wardType', label: '病房類型', type: 'enum',
        options: ['內科', '外科', '婦產', '兒科', '精神', '安寧', '混合'] },
      { key: 'dayShiftRatio', label: '白班護病比', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜護病比', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜護病比', type: 'string' },
      { key: 'leaderSupport', label: 'Leader 協助', type: 'enum',
        options: ['全班協助', '部分協助', '無'] },
      { key: 'invasiveDuties', label: '侵入性處置', type: 'string' },
    ],
  },
  {
    slug: 'icu',
    name: '加護病房',
    short: 'ICU',
    color: '#2E86AB',
    accent: '#A8DADC',
    description: '照護需密集監測的重症病人，第一線面對呼吸器、血流動力監測與各式維生管路。',
    icon: 'activity',
    csvUrl: 'data/mock/icu.csv',
    formUrl: 'participate-icu.html',
    formStatus: 'live',
    specificFields: [
      { key: 'bedbathFreq', label: 'Bedbath 頻率', type: 'enum',
        options: ['QD & PRN', 'QOD & PRN', '其他'] },
      { key: 'ppCareFreq', label: 'PP care 頻率', type: 'enum',
        options: ['QD & PRN', 'QOD & PRN', '其他'] },
      { key: 'dayShiftRatio', label: '白班常態護病比', type: 'string' },
      { key: 'dayPeakRatio', label: '白班最忙時', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜常態護病比', type: 'string' },
      { key: 'eveningPeakRatio', label: '小夜最忙時', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜常態護病比', type: 'string' },
      { key: 'nightPeakRatio', label: '大夜最忙時', type: 'string' },
      { key: 'shiftSystem', label: '班別', type: 'enum',
        options: ['三班制', '兩班制', '其他'] },
      { key: 'eveningAllowanceNonPack', label: '小夜津貼/班(非包班)', type: 'string' },
      { key: 'eveningAllowancePack', label: '小夜津貼/班(包班)', type: 'string' },
      { key: 'nightAllowanceNonPack', label: '大夜津貼/班(非包班)', type: 'string' },
      { key: 'nightAllowancePack', label: '大夜津貼/班(包班)', type: 'string' },
      { key: 'dailyOvertime', label: '每日平均加班時間', type: 'enum',
        options: ['無', '1 小時內', '1-2 小時', '2-3 小時', '4 小時'] },
      { key: 'icuTrainingRequired', label: '硬性規定 ICU Training', type: 'enum',
        options: ['是', '否', '不清楚'] },
      { key: 'icuTrainingContract', label: 'ICU Training 簽約', type: 'enum',
        options: ['是', '否', '無 ICU Training'] },
      { key: 'icuTrainingPeriod', label: 'ICU Training 期間', type: 'string' },
      { key: 'promotionReport', label: '進階制度', type: 'string' },
      { key: 'advancedTherapyTraining', label: 'CVVH/IABP/ECMO 受訓', type: 'multi' },
      { key: 'specialBenefits', label: '特殊福利', type: 'text' },
    ],
  },
  {
    slug: 'er',
    name: '急診',
    short: '急診',
    color: '#E63946',
    accent: '#FAD2CF',
    description: '同時運轉檢傷、急救與留觀，病情與人流難以預測，是全院步調最緊湊的單位。',
    icon: 'siren',
    csvUrl: 'data/mock/er.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'erLevel', label: '急診級別', type: 'enum',
        options: ['重度級', '中度級', '一般級'] },
      { key: 'triageRatio', label: '檢傷人均', type: 'string' },
      { key: 'criticalRatio', label: '重症區人均', type: 'string' },
      { key: 'observationRatio', label: '留觀人均', type: 'string' },
      { key: 'violenceFreq', label: '暴力事件頻率', type: 'enum',
        options: ['每週', '每月', '每季', '罕見'] },
    ],
  },
  {
    slug: 'or',
    name: '手術房',
    short: '手術房',
    color: '#FF6B9D',
    accent: '#FDD5E2',
    description: '負責刷手、流動與恢復室照護，是手術全程不可或缺的一環。',
    icon: 'scissors',
    csvUrl: 'data/mock/or.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'orSpecialty', label: '主要科別', type: 'enum',
        options: ['一般外科', '心臟外科', '神經外科', '骨科', '婦產', '泌尿', '整形外科', '兒外', '眼科', '耳鼻喉', '混合'] },
      { key: 'orRole', label: '工作角色', type: 'enum',
        options: ['流動護理師', '刷手護理師', '恢復室', '麻醉護理', '混合輪替'] },
      { key: 'dailyCases', label: '每日刀數', type: 'string' },
      { key: 'roomCount', label: '手術室數量', type: 'string' },
      { key: 'dayShiftRatio', label: '白班配置 (護理師:刀台)', type: 'string' },
      { key: 'onCallSystem', label: '值班/On-call', type: 'enum',
        options: ['有，常被 call 回', '有，少被 call', '無'] },
    ],
  },
  {
    slug: 'outpatient',
    name: '門診',
    short: '門診',
    color: '#9D4EDD',
    accent: '#E0CFF7',
    description: '協助看診、檢查、衛教與行政，從診所到醫學中心規模落差極大。',
    icon: 'calendar-check',
    csvUrl: 'data/mock/outpatient.csv',
    formUrl: 'participate-outpatient.html',
    formStatus: 'live',
    specificFields: [
      { key: 'clinicType', label: '門診類型', type: 'string' },
      { key: 'clinicsPerNurse', label: '一次顧幾診', type: 'enum',
        options: ['1 診', '2 診', '3 診', '4 診以上'] },
      { key: 'weeklyPatients', label: '就診人數週平均', type: 'enum',
        options: ['300 以下', '300-600', '600-900', '900-1200', '1200 以上'] },
      { key: 'shiftType', label: '班別', type: 'enum',
        options: ['純早診（日班）', '早診＋午診', '含夜診', '輪班制', '其他'] },
      { key: 'pShift', label: 'P 班（PRN）', type: 'enum',
        options: ['是（PRN，需要時才上班）', '否（固定班表）', '部分 PRN'] },
      { key: 'lunchBreak', label: '休息一小時', type: 'enum',
        options: ['有，完整 1 小時', '有，但常被中斷／縮短', '無'] },
      { key: 'clinicOvertimeWeekly', label: '門診逾時週平均', type: 'enum',
        options: ['幾乎不', '每週 1-2 次', '每週 3-4 次', '幾乎每診都逾時'] },
      { key: 'patientComplaints', label: '被申訴頻率', type: 'enum',
        options: ['經常', '偶爾', '罕見', '幾乎沒有'] },
      { key: 'violenceRisk', label: '暴力風險', type: 'enum', options: ['高', '中', '低', '無'] },
      { key: 'salaryGrowth', label: '薪資依年資增加', type: 'enum',
        options: ['有明確調薪制度', '有但幅度小', '幾乎不調', '不清楚'] },
      { key: 'clinicReason', label: '選擇門診原因', type: 'multi' },
      { key: 'specialBenefits', label: '特殊福利', type: 'text' },
    ],
  },
  {
    slug: 'dialysis',
    name: '洗腎室',
    short: '洗腎',
    color: '#06A77D',
    accent: '#C6E8DC',
    description: '照護長期透析（血液、腹膜）的慢性病人，值班與待命制度差異大。',
    icon: 'droplet',
    csvUrl: 'data/mock/dialysis.csv',
    formUrl: 'participate-dialysis.html',
    formStatus: 'live',
    specificFields: [
      { key: 'dialysisType', label: '透析類別', type: 'enum',
        options: ['血液透析', '腹膜透析', '兩者皆有'] },
      { key: 'hdRatio', label: 'HD 常態護病比', type: 'string' },
      { key: 'hdPeakRatio', label: 'HD 最忙時', type: 'string' },
      { key: 'pdCount', label: 'PD 常態護病比', type: 'string' },
      { key: 'pdPeakRatio', label: 'PD 最忙時', type: 'string' },
      { key: 'batchShift', label: '批班制度', type: 'enum', options: ['有', '無'] },
      { key: 'onCallType', label: '值班型態', type: 'string' },
      { key: 'onCallRotation', label: '值班輪值方式', type: 'string' },
      { key: 'restInterval11h', label: '值班 11 小時間隔', type: 'enum', options: ['有', '無'] },
      { key: 'onCallPay', label: '未出勤值班費', type: 'string' },
      { key: 'workDuties', label: '業務內容', type: 'multi' },
      { key: 'specialBenefits', label: '特殊福利', type: 'text' },
    ],
  },
  {
    slug: 'psych',
    name: '精神科',
    short: '精神科',
    color: '#4F46E5',
    accent: '#C7D2FE',
    description: '收治精神急性、慢性與日間照護病人，著重保護室、約束隔離與人權保障，照護邏輯與一般病房截然不同。',
    icon: 'brain',
    csvUrl: 'data/mock/psych.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'psychType', label: '病房類型', type: 'enum',
        options: ['精神急性病房', '精神慢性病房', '日間照護單位', '社區精神復健', '兒童青少年精神', '老年精神', '成癮戒治'] },
      { key: 'dayShiftRatio', label: '白班護病比', type: 'string' },
      { key: 'eveningShiftRatio', label: '小夜護病比', type: 'string' },
      { key: 'nightShiftRatio', label: '大夜護病比', type: 'string' },
      { key: 'hasProtectionRoom', label: '保護室規格', type: 'enum',
        options: ['符合新規格', '較舊但堪用', '無'] },
      { key: 'teamSupport', label: '跨專業團隊', type: 'enum',
        options: ['完整（心理/職能/社工/醫師）', '部分（缺 1-2 種）', '主要靠護理'] },
      { key: 'restraintFreq', label: '約束/隔離頻率', type: 'enum',
        options: ['每日多次', '每週數次', '偶爾', '罕見'] },
      { key: 'violenceFreq', label: '暴力/自傷事件頻率', type: 'enum',
        options: ['每週', '每月', '每季', '罕見'] },
    ],
  },
  {
    slug: 'special',
    name: '檢查/介入',
    short: '檢查/介入',
    color: '#14B8A6',
    accent: '#B7E9E1',
    description: '執行心導管、電燒、內視鏡、血管攝影、高壓氧等檢查與介入治療，技術專精、風險高，常需 on-call 並面對輻射暴露。',
    icon: 'zap',
    csvUrl: 'data/mock/special.csv',
    formUrl: '',
    formStatus: 'coming-soon',
    specificFields: [
      { key: 'specialType', label: '單位類型', type: 'enum',
        options: ['心導管室', '電燒室 (EP Lab)', '內視鏡室', '胃鏡室', '血管攝影室', '介入治療中心', '高壓氧', '其他'] },
      { key: 'dailyCases', label: '每日案件數', type: 'string' },
      { key: 'onCallRequired', label: 'On-call 制度', type: 'enum',
        options: ['有，常被 call', '有，少被 call', '無'] },
      { key: 'radiationExposure', label: '輻射暴露', type: 'enum',
        options: ['高頻率', '中等', '少量', '無'] },
      { key: 'dayShiftRatio', label: '白班人均', type: 'string' },
    ],
  },
  {
    slug: 'other',
    name: '其他',
    short: '其他',
    color: '#64748B',
    accent: '#D1D9E2',
    description: '涵蓋前述場域以外的護理職務：專科護理師、居家／社區、長照、學校、月子中心、公衛，以及廠護／職護、臨床研究（CRA／CRC）、藥廠醫材等較少被看見的職涯。',
    icon: 'briefcase-medical',
    csvUrl: 'data/mock/other.csv',
    formUrl: 'participate-other.html',
    formStatus: 'live',
    specificFields: [
      { key: 'workplaceType', label: '職場類型', type: 'enum',
        options: ['專科護理師', '職護／廠護', '居家護理', '長照機構／護理之家', '學校護理師', '月子中心', '診所／醫美', '藥廠／醫材（MSL/CRA/CRC）', '公共衛生／衛生所', '其他'] },
      { key: 'practiceRegistration', label: '需執業登記', type: 'enum',
        options: ['需要', '不需要', '不清楚'] },
      { key: 'otherCerts', label: '其他證書資格', type: 'multi' },
      { key: 'certRequired', label: '資格是否必備', type: 'enum',
        options: ['是，必備', '否，加分用', '不適用'] },
      { key: 'scheduleSystem', label: '排班制度', type: 'enum',
        options: ['見紅休（週休二日＋國定假日）', '排班制（輪班）', '其他'] },
      { key: 'shiftPattern', label: '輪班型態', type: 'enum',
        options: ['純白班', '需輪小夜', '需輪三班', '其他'] },
      { key: 'fieldWork', label: '需外出值勤', type: 'enum', options: ['是', '否'] },
      { key: 'violenceRisk', label: '暴力風險', type: 'enum', options: ['高', '中', '低', '無'] },
      { key: 'dailyOvertime', label: '每日平均加班', type: 'enum',
        options: ['無', '1 小時內', '1-2 小時', '2-3 小時', '3 小時以上'] },
      { key: 'specialBenefits', label: '特殊福利', type: 'text' },
    ],
  },
];

export function getCategory(slug) {
  return CATEGORIES.find((c) => c.slug === slug) || null;
}

export function getAllFields(slug) {
  const cat = getCategory(slug);
  if (!cat) return COMMON_FIELDS;
  return [...COMMON_FIELDS, ...cat.specificFields];
}
