// 手動補充清單：評鑑合格名單（hospitals.js，一般醫院評鑑）漏收、但實際營運且有
// 護理師執業的機構/院區，於表單機構名稱自動建議時一併納入。
//
// 來源：護病比 VPN 資料中 source:'vpn-only'（對不到評鑑名單）的機構，以健保署
// 特約醫事機構開放資料補上官方名稱與縣市。多為精神科醫院/療養院等走不同評鑑管道者。
// 由 tools/build-hospitals-extra.py 產生（松德院區等共用代號院區於該工具 MANUAL 指定）。

export const HOSPITALS_EXTRA = [
  { name: '衛生福利部草屯療養院', city: '南投縣', level: '區域醫院' },
  { name: '安心醫院', city: '嘉義市', level: '地區醫院' },
  { name: '暘基醫院', city: '基隆市', level: '地區醫院' },
  { name: '維德醫療社團法人基隆維德醫院', city: '基隆市', level: '地區醫院' },
  { name: '宜蘭員山醫療財團法人宜蘭員山醫院', city: '宜蘭縣', level: '地區醫院' },
  { name: '海天醫療社團法人海天醫院', city: '宜蘭縣', level: '地區醫院' },
  { name: '佑青醫療財團法人佑青醫院', city: '屏東縣', level: '地區醫院' },
  { name: '安泰醫療社團法人安泰醫院', city: '屏東縣', level: '地區醫院' },
  { name: '安泰醫療社團法人潮州安泰醫院', city: '屏東縣', level: '地區醫院' },
  { name: '屏安醫療社團法人屏安醫院', city: '屏東縣', level: '地區醫院' },
  { name: '迦樂醫療財團法人迦樂醫院', city: '屏東縣', level: '地區醫院' },
  { name: '南星醫院', city: '彰化縣', level: '地區醫院' },
  { name: '員林郭醫院大村分院', city: '彰化縣', level: '地區醫院' },
  { name: '敦仁醫院', city: '彰化縣', level: '地區醫院' },
  { name: '衛生福利部八里療養院', city: '新北市', level: '區域醫院' },
  { name: '北新醫療社團法人北新醫院', city: '新北市', level: '地區醫院' },
  { name: '名恩療養院', city: '新北市', level: '地區醫院' },
  { name: '怡濟慈園醫療社團法人宏濟神經精神科醫院', city: '新北市', level: '地區醫院' },
  { name: '祐民醫院', city: '新北市', level: '地區醫院' },
  { name: '財團法人臺灣省私立臺北仁濟院附設新莊仁濟醫院', city: '新北市', level: '地區醫院' },
  { name: '培靈醫療社團法人關西醫院', city: '新竹縣', level: '地區醫院' },
  { name: '新仁醫院', city: '新竹縣', level: '地區醫院' },
  { name: '衛生福利部桃園療養院', city: '桃園市', level: '區域醫院' },
  { name: '居善醫院', city: '桃園市', level: '地區醫院' },
  { name: '懷寧醫院', city: '桃園市', level: '地區醫院' },
  { name: '承安醫院', city: '桃園市', level: '地區醫院' },
  { name: '中國醫藥大學附設醫院豐原分院', city: '臺中市', level: '地區醫院' },
  { name: '亞洲大學附屬醫院豐中分院', city: '臺中市', level: '地區醫院' },
  { name: '全民醫院', city: '臺中市', level: '地區醫院' },
  { name: '友仁醫院', city: '臺中市', level: '地區醫院' },
  { name: '宏恩醫院龍安分院', city: '臺中市', level: '地區醫院' },
  { name: '新菩提醫院', city: '臺中市', level: '地區醫院' },
  { name: '杏豐醫院', city: '臺中市', level: '地區醫院' },
  { name: '清海醫院', city: '臺中市', level: '地區醫院' },
  { name: '清濱醫院', city: '臺中市', level: '地區醫院' },
  { name: '維新醫療社團法人臺中維新醫院', city: '臺中市', level: '地區醫院' },
  { name: '美德醫院', city: '臺中市', level: '地區醫院' },
  { name: '臺中市立老人復健綜合醫院(委託財團法人中國醫藥大學興建經營)', city: '臺中市', level: '地區醫院' },
  { name: '財團法人臺灣省私立臺中仁愛之家附設靜和醫院', city: '臺中市', level: '地區醫院' },
  { name: '陽光精神科醫院', city: '臺中市', level: '地區醫院' },
  { name: '三軍總醫院北投分院附設民眾診療服務處', city: '臺北市', level: '區域醫院' },
  { name: '臺北市立聯合醫院松德院區', city: '臺北市', level: '區域醫院' },
  { name: '同仁院醫療財團法人萬華醫院', city: '臺北市', level: '地區醫院' },
  { name: '培靈醫院', city: '臺北市', level: '地區醫院' },
  { name: '德威國際牙醫口腔醫院', city: '臺北市', level: '地區醫院' },
  { name: '衛生福利部嘉南療養院', city: '臺南市', level: '區域醫院' },
  { name: '新生醫院', city: '臺南市', level: '地區醫院' },
  { name: '臺灣基督教門諾會醫療財團法人門諾醫院壽豐分院', city: '花蓮縣', level: '地區醫院' },
  { name: '大千醫療社團法人南勢醫院', city: '苗栗縣', level: '地區醫院' },
  { name: '信安醫療社團法人信安醫院', city: '雲林縣', level: '地區醫院' },
  { name: '育仁醫院', city: '雲林縣', level: '地區醫院' },
  { name: '蔡醫院', city: '雲林縣', level: '地區醫院' },
  { name: '財團法人臺灣省私立高雄仁愛之家附設慈惠醫院', city: '高雄市', level: '區域醫院' },
  { name: '高雄市立凱旋醫院', city: '高雄市', level: '區域醫院' },
  { name: '高雄市立大同醫院（委託財團法人私立高雄醫學大學經營)', city: '高雄市', level: '區域醫院' },
  { name: '上琳醫院', city: '高雄市', level: '地區醫院' },
  { name: '優生婦產科醫院', city: '高雄市', level: '地區醫院' },
  { name: '大東醫院', city: '高雄市', level: '地區醫院' },
  { name: '忠孝泌尿專科醫院', city: '高雄市', level: '地區醫院' },
  { name: '惠仁醫院', city: '高雄市', level: '地區醫院' },
  { name: '愛仁醫療社團法人愛仁醫院', city: '高雄市', level: '地區醫院' },
  { name: '杏永醫院', city: '高雄市', level: '地區醫院' },
  { name: '樂安醫院', city: '高雄市', level: '地區醫院' },
  { name: '泰和醫院', city: '高雄市', level: '地區醫院' },
  { name: '活力得中山脊椎外科醫院', city: '高雄市', level: '地區醫院' },
  { name: '燕巢靜和醫療社團法人燕巢靜和醫院', city: '高雄市', level: '地區醫院' },
  { name: '邱外科醫院', city: '高雄市', level: '地區醫院' },
  { name: '靜和醫院', city: '高雄市', level: '地區醫院' },
  { name: '顏威裕醫院', city: '高雄市', level: '地區醫院' },
];
